version: '3'

services:

  site:
    hostname: site
    image: ivozzo/site
    build:
      context: ./server
      dockerfile: Dockerfile
    links:
      - mongodb
    depends_on: 
      - "mongodb"
    ports:
      - "8021:8021"
    networks:
      - database-link
    entrypoint: /docker-entrypoint.sh -npm

  mongodb:
    hostname: mongodb
    image: mongo
    networks:
      - database-link
    ports:
      - "27017:27017"

networks:
    database-link:
      driver: bridge
