version: '3'

services:

  modserver-istance:
    build:
      context: ./server
      dockerfile: Dockerfile
    links:
      - mongodb-istance
    depends_on: 
      - "mongodb-istance"
    ports:
      - "8021:8021"
    networks:
      - database-link

  mongodb-istance:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    networks:
      - database-link
    ports:
      - "27017:27017"

networks:
    database-link:
      driver: bridge
